### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tgrabiec** [ruediger/Boost-Pretty-Printer#29]
I get this when I try to install the printers from gdb:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/remote/home/tgrabiec/src/Boost-Pretty-Printer/boost/printers.py", line 1223
    return long(str(parse_and_eval('*((void**)' + str(node_ptr) + ')')), 16) & (~1L)
                                                                                  ^
SyntaxError: invalid syntax
Error while executing Python code.
```

GDB version:

```
GNU gdb (Ubuntu 7.11-0ubuntu1) 7.11
```

**Comment by mateidavid** [comment]
Try #23 .

**Comment by serup** [comment]
when will this fix be released ??

**Comment by mbalabin** [comment]
Seems to be fixed in current master
